name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered."

      - run: echo "🖥️ Running on ${{ runner.os }}"

      - run: echo "🌱 Branch: ${{ github.ref }}"

      - name: Checkout repository code
        uses: actions/checkout@v4

      - run: echo "💡 Repository cloned successfully."

      - name: List files in repository
        run: ls ${{ github.workspace }}

      - run: echo "✅ Job status iss ${{ job.status }}"
